USE `renren`;
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`(
`id` int(8) NOT NULL PRIMARY KEY AUTO_INCREMENT,
`nickName` varchar(20) NOT NULL,
`birth` INT(4) NOT NULL,
`where` VARCHAR(100) NOT NULL,
`home` VARCHAR(100) NOT NULL,
`albumHome` VARCHAR(100) NOT NULL,
`avatarAlbum` VARCHAR(100) NOT NULL,
`isFetch` BOOLEAN NOT NULL DEFAULT FALSE
)